platform :ios, '6.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking'
pod 'BlocksKit'
pod 'ReactiveCocoa', '~>2.3'
pod 'MagicalRecord'
pod 'SSToolkit', '~>2.0.0'
pod 'Nimbus', '~> 1.2.0'
pod 'pop', '~> 1.0.5'