platform :ios, '6.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking'
pod 'BlocksKit'
pod 'ReactiveCocoa', '~>2.3'
pod 'MagicalRecord'
pod 'SSToolkit', '~>2.0.0'
pod 'Nimbus', '~> 1.2.0'
pod 'pop', '~> 1.0.5'
pod 'PonyDebugger', '~> 0.3.1'
pod 'RDVTabBarController'
pod 'TMCache','~>1.2.0'
pod 'CocoaAsyncSocket','~>7.3.5'
pod 'MBProgressHUD', '~> 0.8'
pod 'ZipArchive','~>1.2.0'